config/routes.rb
Rails.application.routes.draw do
  get 'sales/show'

  root "static_pages#home"
  post '/', to: 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  get '/signup', to: 'users#new'
  post '/signup',  to: 'users#create'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/search', to: 'search#new'
  post '/search', to: 'search#create'

  get 'carts/:id', to: 'carts#show', as: 'cart'
  delete 'carts/:id', to: 'carts#destroy'

  post 'items/:id/add', to: 'items#add_quantity', as: 'item_add'
  post 'items/:id/reduce', to: 'items#reduce_quantity', as: 'item_reduce'
  post 'items/:id', to: 'items#create', as: 'item_create'
  get 'items/:id', to: 'items#show', as: 'item'
  delete 'items/:id', to: 'items#destroy'


  resources :users do
    member do
      get :likes
    end
  end

  resources :products
  resources :purchases
  resources :favorites, only: [:create, :destroy]
  resources :stocks, only: [:new, :create, :edit, :update]
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :items, dependent: :destroy
  has_many :products, through: :items


  def sub_total
    sum = 0
    self.items.each do |item|
      sum += item.total_price
    end
    return sum
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
before_action :current_cart

  def show
    @cart = @current_cart
  end

  # def create
  # end
  #
  # def edit
  # end
  #
  # def update
  # end

  def destroy
    @cart = @current_cart
    @cart.destroy
    session[:cart_id] = nil
    redirect_to root_path
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/show.html.erb
<% provide(:title, "カート一覧") %>

<h1>カート一覧</h1>

<ul>
  <% @cart.items.each do |item| %>
    <li><h4>
      商品名: <%= item.product.name %> / 価格: <%= number_to_currency(item.product.price, unit: "￥", precision: 0) %> / サイズ: <%= Size.find(item[:size_id]).name %> / 数量: <%= item.quantity %> / 小計: <%= number_to_currency(item.total_price, unit: "￥", precision: 0) %>
    </h4></li>
    <table>
      <tr>
        <td width="200">
          <%= image_tag item.product.icon.url, :size =>'150x120' if item.product.icon? %>
          <h4><%= "Sorry, the image does not exist." if !item.product.icon? %></h4>
        </td>
        <td>
          <ul><h4>
            <li><%= link_to "１つ追加", item_add_path(:id => item), method: :post %></li><br>
            <li><%= link_to "１つ減らす", item_reduce_path(:id => item), method: :post %></li><br>
            <li><%= link_to "カートから削除", item_path(item), method: :delete %></li>
          </h4></ul>
        </td>
      </tr>
    </table><br>
  <% end %><br>
</ul>

<h3>合計金額: <%= number_to_currency(@cart.sub_total, unit: "￥", precision: 0) %></h3>

<h3><%= link_to "会計へ進む", new_purchase_path %></h3>

<h3><%= link_to "カートを空にする", cart_path(@current_cart),method: :delete, data: {confirm: "本当によろしいですか？"} %></h3>