config/routes.rb
Rails.application.routes.draw do
  get 'sales/show'

  root "static_pages#home"
  post '/', to: 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  get '/signup', to: 'users#new'
  post '/signup',  to: 'users#create'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/search', to: 'search#new'
  post '/search', to: 'search#create'

  get 'carts/:id', to: 'carts#show', as: 'cart'
  delete 'carts/:id', to: 'carts#destroy'

  post 'items/:id/add', to: 'items#add_quantity', as: 'item_add'
  post 'items/:id/reduce', to: 'items#reduce_quantity', as: 'item_reduce'
  post 'items/:id', to: 'items#create', as: 'item_create'
  get 'items/:id', to: 'items#show', as: 'item'
  delete 'items/:id', to: 'items#destroy'


  resources :users do
    member do
      get :likes
    end
  end

  resources :products
  resources :purchases
  resources :favorites, only: [:create, :destroy]
  resources :stocks, only: [:new, :create, :edit, :update]
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :items, dependent: :destroy
  has_many :favorites, foreign_key: 'product_id', dependent: :destroy
  has_many :purchases
  has_many :stocks, dependent: :destroy
  has_many :users, through: :favorites
  belongs_to :category
  belongs_to :brand
  belongs_to :user, optional: true
  default_scope -> {order(created_at: :desc)}
  mount_uploader :icon, IconUploader
  validate :icon_size
  validates :name, presence: :true, length: { maximum: 255 }
  validates :category_id, presence: :true
  validates :brand_id, presence: :true
  validates :price, presence: :true, numericality: { greater_than_or_equal_to: 0 }
  validates :detail, presence: :true, length: { maximum: 500 }

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :logged_in_user, only: [:new, :create, :edit, :update, :destroy]
  before_action :admin_user,     only: [:new, :create, :edit, :update, :destroy]

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:success] = "商品が追加されました!"
      redirect_to new_product_path
    else
      render 'new'
    end
  end

  def show
    if !Product.where(id: params[:id]).exists?
      flash[:danger] = "現在その商品は取り扱われておりません。"
      redirect_to purchases_path
    else
      @product       = Product.find(params[:id])

      #Stocksテーブルの中から、商品詳細に表示する商品の
      #idに一致するレコードを全て@product_sizesに代入
      #一つの商品はいくつかのsize_idを持つので、一致するレコードが
      #ハッシュ化され、配列の中に入れ込まれる（[{}, {}]みたいに）
      @product_sizes = Stock.where("product_id = ?", params[:id]).order("size_id").to_a
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(product_params)
      flash[:success] = "商品情報が変更されました"
      redirect_to @product
    else
      flash[:danger] = "商品情報変更に失敗しました"
      render 'edit'
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:success] = "商品は削除されました"
    redirect_to root_url
  end


private

  def product_params
     params.require(:product).permit(:name, :category_id, :brand_id,
                                  :price, :detail, :icon)
  end
end

app/helpers/products_helper.rb
module ProductsHelper


  # def product_size
  #   Size.where(Stock.where(product_id: @product.id)[:size_id])
  # end
  #
  #
  def each_size(size_id)
    Size.find(size_id).name
  end
  #
  #
  # def stock_amount
  #   Stock.find_by(product_id: @product.id).stock
  # end
  #
  def each_amount(size_id)
    Stock.where(product_id: @product.id).find_by(size_id: size_id).stock
  end
  #
  # def stocks(size_id)
  #   Stock.where(product_id: @product.id).find_by(size_id: size_id)
  # end
  #
  # def size_ids(hoge)
  #   size_ids = []
  #   hoge.each do |id|
  #     size_ids << id[:size_id]
  #   end
  #   return size_ids.sort
  # end

end

app/views/products/_product.html.erb
<li>
  <span class="product_name">
  <%= link_to product.name, product_path(product.id) %></span>
  <table>
    <tr>
      <td width="240">
        <%= image_tag product.icon.url, :size =>'230x180' if product.icon? %>
        <h4><%= "Sorry, the image does not exist." if !product.icon? %></h4>
      </td>
      <td width="500">
        <span class="product_info">
          カテゴリー: <%= Category.find(product.category_id).name %>
        </span>

        <span class="product_info">
          ブランド: <%= Brand.find(product.brand_id).name %>
        </span>

        <span class="product_info">
          価格: ￥<%= product.price %>
        </span>

        <span class="timestamp">
          Added <%= time_ago_in_words(product.created_at) %> ago.
        </span>

        <span class="timestamp">
          Updated <%= time_ago_in_words(product.updated_at) %> ago.
        </span>
      </td>
    </tr>
  </table>
    <span class="timestamp">
      <% if logged_in? && current_user.admin %>
        <%= link_to "商品情報変更", edit_product_path(product.id) %>
        <%= link_to "商品削除", product_path(product.id), method: :delete,
                                         data: { confirm: "You sure?" } %>
        <%= link_to "新規ストック追加", new_stock_path(product_id: product.id) %>
        <%= link_to "ストック数変更", edit_stock_path(id: product.id) %>
      <% end %>
    </span>
</li>

app/views/products/edit.html.erb
<% provide(:title, "Update a product") %>

<h1>商品情報変更</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@product) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="field">
        <%= f.label :name  %>
        <%= f.text_field :name, placeholder: "Name", class: 'form-control' %>

        <% if false %>
        <%= f.label :picture  %>
        <%= f.file_field :picture, class: 'form-control' %>
        <% end %>

        <%= f.label :カテゴリ名  %>
        <%= f.collection_select :category_id, Category.all, :id, :name, class: 'form-control' %>
        <%= f.label :ブランド名 %>
        <%= f.collection_select :brand_id, Brand.all, :id, :name, class: 'form-control' %>
        <%= f.label :価格 %>
        <%= f.number_field :price, placeholder: "半角数字で入力してください", class: 'form-control' %>
        <%= f.label :商品詳細 %>
        <%= f.text_area :detail, class: 'form-control' %>
        <%= f.label :アイコン %>
        <%= f.file_field :icon, accept: 'image/jpeg,image/gif,image/png', class: 'form-control' %>
      </div>
      <%= f.submit "商品情報を更新する", class: "btn btn-primary" %>
    <% end %>

    <script type="text/javascript">
      $('#micropost_picture').bind('change', function() {
        var size_in_megabytes = this.files[0].size/1024/1024;
        if (size_in_megabytes > 5) {
          alert('Maximum file size is 5MB. Please choose a smaller file.');
        }
      });
    </script>

  </div>
</div>

app/views/products/new.html.erb
<% provide(:title, 'Add product') %>
<% provide(:button_text, '商品を追加する') %>
<h1>商品追加</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@product) do |f| %>
      <%= render 'shared/error_messages', object: @product %>

      <%= f.label :商品名 %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :カテゴリ %>
      <%= f.collection_select :category_id, Category.all, :id, :name, class: 'form-control' %>

      <%= f.label :ブランド %>
      <%= f.collection_select :brand_id, Brand.all, :id, :name, class: 'form-control' %>

      <%= f.label :価格 %>
      <%= f.number_field :price, class: 'form-control', min:0, placeholder: '半角数字で価格を入力', value: nil%>

      <%= f.label :商品詳細（500字以内） %>
      <%= f.text_area :detail, class: 'form-control' %>

      <%= f.label :アイコン %>
      <%= f.file_field :icon, accept: 'image/jpeg,image/gif,image/png', class: 'form-control' %>

      <%= f.submit yield(:button_text), class: "btn btn-primary" %>
    <% end %>

    <script type="text/javascript">
      $('#product_icon').bind('change', function() {
        var size_in_megabytes = this.files[0].size/1024/1024;
        if (size_in_megabytes > 5) {
          alert('Maximum file size is 5MB. Please choose a smaller file.');
        }
      });
    </script>

  </div>
</div>

app/views/products/show.html.erb
<% provide(:title, @product.name) %>

<h1>商品詳細</h1>

<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <ol class="products">
      <span class="product_name">
      <%= link_to @product.name, product_path(@product.id) %></span>
      <table>
        <tr>
          <td width="470">
            <%= image_tag @product.icon.url if @product.icon? %>
            <h4><%= "Sorry, the image does not exist." if !@product.icon? %></h4>

          </td>
          <td width="500">
            <span class="product_info">カテゴリー: <%= Category.find(@product.category_id).name %></span>
            <span class="product_info">ブランド: <%= Brand.find(@product.category_id).name %></span>
            <span class="product_info">価格: ¥<%= @product.price %></span>
            <span class="detail jumbotron"><%= @product.detail %></span>

            <% if @product_sizes.empty? %>
              <h3>ただいまこちらの商品はお取り扱いしておりません。</h3>
            <% else %>
              <ol class="stocks">
                <% @product_sizes.each do |each_product| %>
                  <% size_id      = each_product[:size_id] %>
                  <% product_id   = each_product[:product_id] %>
                  <% if each_amount(size_id) > 100 %>
                    <h4>サイズ: <%= each_size(size_id) %> / 在庫: ○</h4>
                  <% elsif each_amount(size_id) > 0 %>
                    <h4>サイズ: <%= each_size(size_id) %> / 在庫数: <%= each_amount(size_id) %></h4>
                  <% else %>
                    <h4>サイズ: <%= each_size(size_id) %> / 在庫: 品切れ</h4>
                  <% end %>
                <% end %>
              </ol>
              <%= form_with url: item_create_path do |form| %>
                <%= hidden_field_tag :product_id, @product.id %>
                <%= form.label :サイズ %>
                <%= form.collection_select(:size_id, Size.where(id: size_ids(@product_sizes)), :id, :name) %>
                <%= form.number_field :quantity, class: 'form-control', min:1, max:100, placeholder: '購入数を半角数字で入力してください', value: 1%>
                <%= form.submit "カートに追加", class: 'btn btn-primary' %>
              <% end %>
            <% end %>
          </td>
        </tr>
      </table><br><br>

      <% if current_user.favproduct?(@product) %>
        <%= form_for(current_user.favorites.find_by(product_id: @product.id), html: { method: :delete }) do |f| %>
          <%= hidden_field_tag :product_id, @product.id %>
          <%= f.submit 'お気に入り登録解除', class: 'btn btn-danger' %>
        <% end %>
      <% else %>
        <%= form_for(current_user.favorites.build) do |f| %>
          <%= hidden_field_tag :product_id, @product.id %>
          <%= f.submit 'お気に入り登録', class: 'btn btn-default' %>
        <% end %>
      <% end %>
    </ol>
  </div>
</div>