config/routes.rb
Rails.application.routes.draw do
  get 'sales/show'

  root "static_pages#home"
  post '/', to: 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  get '/signup', to: 'users#new'
  post '/signup',  to: 'users#create'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/search', to: 'search#new'
  post '/search', to: 'search#create'

  get 'carts/:id', to: 'carts#show', as: 'cart'
  delete 'carts/:id', to: 'carts#destroy'

  post 'items/:id/add', to: 'items#add_quantity', as: 'item_add'
  post 'items/:id/reduce', to: 'items#reduce_quantity', as: 'item_reduce'
  post 'items/:id', to: 'items#create', as: 'item_create'
  get 'items/:id', to: 'items#show', as: 'item'
  delete 'items/:id', to: 'items#destroy'


  resources :users do
    member do
      get :likes
    end
  end

  resources :products
  resources :purchases
  resources :favorites, only: [:create, :destroy]
  resources :stocks, only: [:new, :create, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  private

    # アップロードされた画像のサイズをバリデーションする
    def icon_size
      if icon.size > 5.megabytes
        errors.add(:icon, "should be less than 5MB")
      end
    end
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :products
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :items, dependent: :destroy
  has_many :products, through: :items


  def sub_total
    sum = 0
    self.items.each do |item|
      sum += item.total_price
    end
    return sum
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :product
  belongs_to :size
  belongs_to :cart
  belongs_to :purchase, optional: true
  validates :quantity, presence: true, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 100 }
  validates :size_id, presence: true

  def total_price
    self.quantity * self.product.price
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :items, dependent: :destroy
  has_many :favorites, foreign_key: 'product_id', dependent: :destroy
  has_many :purchases
  has_many :stocks, dependent: :destroy
  has_many :users, through: :favorites
  belongs_to :category
  belongs_to :brand
  belongs_to :user, optional: true
  default_scope -> {order(created_at: :desc)}
  mount_uploader :icon, IconUploader
  validate :icon_size
  validates :name, presence: :true, length: { maximum: 255 }
  validates :category_id, presence: :true
  validates :brand_id, presence: :true
  validates :price, presence: :true, numericality: { greater_than_or_equal_to: 0 }
  validates :detail, presence: :true, length: { maximum: 500 }

end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :user
  has_many :items
  has_many :products, through: :items
  belongs_to :product, optional: true

  validates :destination_name, presence: true, length: { maximum: 255 }
  VALID_CODE_REGEX = /\A[0-9]+[0-9]+[0-9]+[-]+[0-9]+[0-9]+[0-9]+[0-9]\z/i
  validates :destination_postal_code, presence: true, length: { is: 8 }, format: { with: VALID_CODE_REGEX }
  validates :destination_address, presence: true, length: { maximum: 255 }
  validates :credit_number, presence: true, length: { in: 14..16 }
  mount_uploader :icon, IconUploader
  validate :icon_size

end

app/models/size.rb
class Size < ApplicationRecord
  has_many :items
  has_many :stocks
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :product
  belongs_to :size
  validates :stock, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :purchases
  has_many :carts, dependent: :destroy
  has_many :favorites
  has_many :products
  has_many :favproducts, through: :favorites, source: :product

  attr_accessor :remember_token
  before_save :downcase_email
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  #VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  VALID_POSTAL_CODE_REGEX = /\A\d{3}[-]\d{4}\z/
  validates :postal_code, presence: true, length: { is: 8 },
                    format: { with: VALID_POSTAL_CODE_REGEX }
  validates :address, presence: true, length: { maximum: 255 }
  has_secure_password
  validates :password, presence: true, length: { in: 6..15 }

  # 渡された文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返す
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # 永続セッションのためにユーザーをデータベースに記憶する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # 渡されたトークンがダイジェストと一致したらtrueを返す
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

 # ユーザーのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end


 #お気に入り周りの機能
  def like(product)
    favorites.find_or_create_by(product_id: product.id)
  end

  def unlike(product)
    favorite = favorites.find_by(product_id: product.id)
    favorite.destroy if favorite
  end

  #お気に入り判定
  def favproduct?(product)
    self.favproducts.include?(product)
  end

  private

    def downcase_email
      self.email = email.downcase
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper


  # def product_size
  #   Size.where(Stock.where(product_id: @product.id)[:size_id])
  # end
  #
  #
  def each_size(size_id)
    Size.find(size_id).name
  end
  #
  #
  # def stock_amount
  #   Stock.find_by(product_id: @product.id).stock
  # end
  #
  def each_amount(size_id)
    Stock.where(product_id: @product.id).find_by(size_id: size_id).stock
  end
  #
  # def stocks(size_id)
  #   Stock.where(product_id: @product.id).find_by(size_id: size_id)
  # end
  #
  # def size_ids(hoge)
  #   size_ids = []
  #   hoge.each do |id|
  #     size_ids << id[:size_id]
  #   end
  #   return size_ids.sort
  # end

end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # 渡されたユーザーでログインする
  def log_in(user)
    session[:user_id] = user.id
  end

  # ユーザーを永続的セッションに記憶する
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # 与えられたユーザーがログイン済みユーザーであればtrueを返す
  def current_user?(user)
    user == current_user
  end

  # 記憶トークンcookieに対応するユーザーを返す
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # ユーザーがログインしていればtrue、その他ならfalseを返す
  def logged_in?
    !current_user.nil?
  end

  # 永続的セッションを破棄する
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end



  # 現在のユーザーがログアウトする
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end


  # 記憶したURL (もしくはデフォルト値) にリダイレクト
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # アクセスしようとしたURLを覚えておく
  def store_location
    session[:forwarding_url] = request.url if request.get?
  end
end

app/helpers/stocks_helper.rb
module StocksHelper
  def size_ids(hoge)
    size_ids = []
    hoge.each do |id|
      size_ids << id[:size_id]
    end
    return size_ids.sort
  end
end

app/helpers/users_helper.rb
module UsersHelper

  # 引数で与えられたユーザーのGravatar画像を返す
  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Produced by Kazuki Koga
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "gaga town", root_path, id: "logo" %>

    <nav>
      <ul class="nav navbar-nav navbar-left">
      <% if logged_in? %>
        <li class="search_window">
          <%= form_tag search_path, method: :get do %>
            <%= text_field_tag :name, params[:name], size: 30, placeholder: "何かお探しですか？", class:'form-control' %></li>
            <li class="search_window"><%= submit_tag :🔍, class:'btn btn-primary' %>
          <% end %>
        </li>
      <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "ホーム", root_path %></li>
        <% if logged_in? %>
          <li><%= link_to "カート", cart_path(@current_cart) %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              アカウント <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "ユーザー情報変更", edit_user_path(current_user) %></li>
              <li><%= link_to "お気に入りリスト", likes_user_path(current_user) %></li>
              <li><%= link_to "購入履歴", purchases_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "ログアウト", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "ログイン", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag 'application', media: 'all',
'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
   <%= render 'layouts/header' %>
   <div class="container">
     <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
     <% end %>
     <%= yield %>
     <%= render 'layouts/footer' %>
     <%= debug(params) if Rails.env.development? %>
   </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_fav_index.html.erb
<% if @favproducts.any? %>
  <ol class="products">
    <%= render @favproducts %>
  </ol>
  <% if false %>
  <%= will_paginate @favproducts %>
  <% end %>
<% end %>

app/views/shared/_product_index.html.erb
  <% if @feed_items.any? %>
    <ol class="products">
      <%= render @feed_items %>
    </ol>
    <%= will_paginate @feed_items %>
  <% end %>

app/views/shared/_purchase_index.html.erb
<% if @purchases.any? %>
  <ol class="products">
    <%= render @purchases %>
  </ol>
  <%= will_paginate @purchases %>
<% end %>

app/views/shared/_search_form.html.erb
<h3>商品検索</h3>
<form accept-charset="UTF-8" action="/search" class="search"
      id="search" method="get">

  <div class="field">
    <label for="category">カテゴリー</label>
    <select id="category" name="category_id" class="form-control">
      <option value=""></option>
      <option value="1">トップス</option>
      <option value="2">ジャケット・アウター</option>
      <option value="3">パンツ</option>
      <option value="4">オールインワン</option>
      <option value="5">スカート</option>
      <option value="6">ワンピース</option>
      <option value="7">スーツ・ネクタイ</option>
      <option value="8">バック</option>
      <option value="9">シューズ</option>
      <option value="10">時計</option>
    </select>

    <label for="brand">ブランド</label>
    <select id="brand" name="brand_id" class="form-control">
      <option value=""></option>
      <option value="1">adidas</option>
      <option value="2">BEAMS</option>
      <option value="3">Champion</option>
      <option value="4">Dr.Martens</option>
      <option value="5">Edwin</option>
      <option value="6">Francfranc</option>
      <option value="7">GUCCI</option>
      <option value="8">H&M</option>
      <option value="9">JINS</option>
      <option value="10">KATE</option>
    </select>

    <label for="price">価格帯(上限)</label>
    <input id="price" name="price" type="number" placeholder="Price(max)" min="0" class="form-control" />
  </div><br>
  <input class="btn btn-primary" name="commit" type="submit"
         value="Search" />
</form><br>

<h3>
<% if logged_in? && current_user.admin %>
  <%= link_to "商品追加", new_product_path %>
<% end %>
</h3>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>